// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: laptop_message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Laptop struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Brand    string                 `protobuf:"bytes,2,opt,name=brand,proto3" json:"brand,omitempty"`
	Name     string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Cpu      *CPU                   `protobuf:"bytes,4,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Ram      *Memory                `protobuf:"bytes,5,opt,name=ram,proto3" json:"ram,omitempty"`
	Gpus     []*GPU                 `protobuf:"bytes,6,rep,name=gpus,proto3" json:"gpus,omitempty"`
	Storages []*Storage             `protobuf:"bytes,7,rep,name=storages,proto3" json:"storages,omitempty"`
	Screen   *Screen                `protobuf:"bytes,8,opt,name=screen,proto3" json:"screen,omitempty"`
	Keyboard *Keyboard              `protobuf:"bytes,9,opt,name=keyboard,proto3" json:"keyboard,omitempty"`
	// Types that are valid to be assigned to Weight:
	//
	//	*Laptop_WeightKg
	//	*Laptop_WeightLb
	Weight        isLaptop_Weight        `protobuf_oneof:"weight"`
	PriceUsd      float64                `protobuf:"fixed64,12,opt,name=price_usd,json=priceUsd,proto3" json:"price_usd,omitempty"`
	ReleaseYear   uint32                 `protobuf:"varint,13,opt,name=release_year,json=releaseYear,proto3" json:"release_year,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Laptop) Reset() {
	*x = Laptop{}
	mi := &file_laptop_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Laptop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Laptop) ProtoMessage() {}

func (x *Laptop) ProtoReflect() protoreflect.Message {
	mi := &file_laptop_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Laptop.ProtoReflect.Descriptor instead.
func (*Laptop) Descriptor() ([]byte, []int) {
	return file_laptop_message_proto_rawDescGZIP(), []int{0}
}

func (x *Laptop) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Laptop) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *Laptop) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Laptop) GetCpu() *CPU {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *Laptop) GetRam() *Memory {
	if x != nil {
		return x.Ram
	}
	return nil
}

func (x *Laptop) GetGpus() []*GPU {
	if x != nil {
		return x.Gpus
	}
	return nil
}

func (x *Laptop) GetStorages() []*Storage {
	if x != nil {
		return x.Storages
	}
	return nil
}

func (x *Laptop) GetScreen() *Screen {
	if x != nil {
		return x.Screen
	}
	return nil
}

func (x *Laptop) GetKeyboard() *Keyboard {
	if x != nil {
		return x.Keyboard
	}
	return nil
}

func (x *Laptop) GetWeight() isLaptop_Weight {
	if x != nil {
		return x.Weight
	}
	return nil
}

func (x *Laptop) GetWeightKg() float64 {
	if x != nil {
		if x, ok := x.Weight.(*Laptop_WeightKg); ok {
			return x.WeightKg
		}
	}
	return 0
}

func (x *Laptop) GetWeightLb() float64 {
	if x != nil {
		if x, ok := x.Weight.(*Laptop_WeightLb); ok {
			return x.WeightLb
		}
	}
	return 0
}

func (x *Laptop) GetPriceUsd() float64 {
	if x != nil {
		return x.PriceUsd
	}
	return 0
}

func (x *Laptop) GetReleaseYear() uint32 {
	if x != nil {
		return x.ReleaseYear
	}
	return 0
}

func (x *Laptop) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type isLaptop_Weight interface {
	isLaptop_Weight()
}

type Laptop_WeightKg struct {
	WeightKg float64 `protobuf:"fixed64,10,opt,name=weight_kg,json=weightKg,proto3,oneof"`
}

type Laptop_WeightLb struct {
	WeightLb float64 `protobuf:"fixed64,11,opt,name=weight_lb,json=weightLb,proto3,oneof"`
}

func (*Laptop_WeightKg) isLaptop_Weight() {}

func (*Laptop_WeightLb) isLaptop_Weight() {}

var File_laptop_message_proto protoreflect.FileDescriptor

const file_laptop_message_proto_rawDesc = "" +
	"\n" +
	"\x14laptop_message.proto\x12\x11techschool_pcbook\x1a\x17processor_message.proto\x1a\x14memory_message.proto\x1a\x15storage_message.proto\x1a\x14screen_message.proto\x1a\x16keyboard_message.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xac\x04\n" +
	"\x06Laptop\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05brand\x18\x02 \x01(\tR\x05brand\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12(\n" +
	"\x03cpu\x18\x04 \x01(\v2\x16.techschool_pcbook.CPUR\x03cpu\x12+\n" +
	"\x03ram\x18\x05 \x01(\v2\x19.techschool_pcbook.MemoryR\x03ram\x12*\n" +
	"\x04gpus\x18\x06 \x03(\v2\x16.techschool_pcbook.GPUR\x04gpus\x126\n" +
	"\bstorages\x18\a \x03(\v2\x1a.techschool_pcbook.StorageR\bstorages\x121\n" +
	"\x06screen\x18\b \x01(\v2\x19.techschool_pcbook.ScreenR\x06screen\x127\n" +
	"\bkeyboard\x18\t \x01(\v2\x1b.techschool_pcbook.KeyboardR\bkeyboard\x12\x1d\n" +
	"\tweight_kg\x18\n" +
	" \x01(\x01H\x00R\bweightKg\x12\x1d\n" +
	"\tweight_lb\x18\v \x01(\x01H\x00R\bweightLb\x12\x1b\n" +
	"\tprice_usd\x18\f \x01(\x01R\bpriceUsd\x12!\n" +
	"\frelease_year\x18\r \x01(\rR\vreleaseYear\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\b\n" +
	"\x06weightB)\n" +
	"\x1fcom.github.techschool.pcbook.pbP\x01Z\x04.;pbb\x06proto3"

var (
	file_laptop_message_proto_rawDescOnce sync.Once
	file_laptop_message_proto_rawDescData []byte
)

func file_laptop_message_proto_rawDescGZIP() []byte {
	file_laptop_message_proto_rawDescOnce.Do(func() {
		file_laptop_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_laptop_message_proto_rawDesc), len(file_laptop_message_proto_rawDesc)))
	})
	return file_laptop_message_proto_rawDescData
}

var file_laptop_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_laptop_message_proto_goTypes = []any{
	(*Laptop)(nil),                // 0: techschool_pcbook.Laptop
	(*CPU)(nil),                   // 1: techschool_pcbook.CPU
	(*Memory)(nil),                // 2: techschool_pcbook.Memory
	(*GPU)(nil),                   // 3: techschool_pcbook.GPU
	(*Storage)(nil),               // 4: techschool_pcbook.Storage
	(*Screen)(nil),                // 5: techschool_pcbook.Screen
	(*Keyboard)(nil),              // 6: techschool_pcbook.Keyboard
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_laptop_message_proto_depIdxs = []int32{
	1, // 0: techschool_pcbook.Laptop.cpu:type_name -> techschool_pcbook.CPU
	2, // 1: techschool_pcbook.Laptop.ram:type_name -> techschool_pcbook.Memory
	3, // 2: techschool_pcbook.Laptop.gpus:type_name -> techschool_pcbook.GPU
	4, // 3: techschool_pcbook.Laptop.storages:type_name -> techschool_pcbook.Storage
	5, // 4: techschool_pcbook.Laptop.screen:type_name -> techschool_pcbook.Screen
	6, // 5: techschool_pcbook.Laptop.keyboard:type_name -> techschool_pcbook.Keyboard
	7, // 6: techschool_pcbook.Laptop.updated_at:type_name -> google.protobuf.Timestamp
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_laptop_message_proto_init() }
func file_laptop_message_proto_init() {
	if File_laptop_message_proto != nil {
		return
	}
	file_processor_message_proto_init()
	file_memory_message_proto_init()
	file_storage_message_proto_init()
	file_screen_message_proto_init()
	file_keyboard_message_proto_init()
	file_laptop_message_proto_msgTypes[0].OneofWrappers = []any{
		(*Laptop_WeightKg)(nil),
		(*Laptop_WeightLb)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_laptop_message_proto_rawDesc), len(file_laptop_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_laptop_message_proto_goTypes,
		DependencyIndexes: file_laptop_message_proto_depIdxs,
		MessageInfos:      file_laptop_message_proto_msgTypes,
	}.Build()
	File_laptop_message_proto = out.File
	file_laptop_message_proto_goTypes = nil
	file_laptop_message_proto_depIdxs = nil
}
